import React from "react";

const Why = () => {
  return (
    <section id="features-3" class="pb-60 features-section division">
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-lg-10 col-xl-8">
            <div className="section-title title-01 mb-80">
              <h2 className="h2-md">Why you can't be left out</h2>
              <p className="p-xl">
                The opportunity is open to everyone and users from aroung the
                globe have keyed in to take control of their finances and
                cashflow rate. The platform has been designed to offer everyone
                a simple sales experience{" "}
              </p>
            </div>
          </div>
        </div>
        <div className="fbox-3-wrapper text-center">
          <div className="row row-cols-1 row-cols-md-2 row-cols-lg-3">
            <div className="col">
              <div
                className="fbox-3 pc-15 mb-40 wow fadeInUp"
                style={{ visibility: "visible", animationName: "fadeInUp" }}
              >
                <div className="fbox-ico-center ico-rounded-lg ico-45 bg-tra-purple purple-color">
                  <span className="flaticon-idea"></span>
                </div>
                <div className="fbox-text-center">
                  <h5 className="h5-md">Zero Transaction Fees</h5>
                  <p className="p-lg">
                    All your fund transfers and cash withdrawal to your personal
                    bank account are totally free of charge
                  </p>
                </div>
              </div>
            </div>
            <div className="col">
              <div
                className="fbox-3 pc-15 mb-40 wow fadeInUp"
                style={{ visibility: "visible", animationName: "fadeInUp" }}
              >
                <div className="fbox-ico-center ico-rounded-lg ico-45 bg-tra-purple purple-color">
                  <span className="flaticon-smartphone"></span>
                </div>
                <div className="fbox-text-center">
                  <h5 className="h5-md">Adaptable Tricks</h5>
                  <p className="p-lg">
                    You have access to a kind of "copy & paste" trick that have
                    delivered results to successful champions
                  </p>
                </div>
              </div>
            </div>
            <div className="col">
              <div
                className="fbox-3 pc-15 mb-40 wow fadeInUp"
                style={{ visibility: "visible", animationName: "fadeInUp" }}
              >
                <div className="fbox-ico-center ico-rounded-lg ico-45 bg-tra-purple purple-color">
                  <span className="flaticon-algorithm"></span>
                </div>
                <div className="fbox-text-center">
                  <h5 className="h5-md">Organized Campeign</h5>
                  <p className="p-lg">
                    You can control where to focus your efforts to generate the
                    kind of result you desire to generate
                  </p>
                </div>
              </div>
            </div>
            <div className="col">
              <div
                className="fbox-3 pc-15 mb-40 wow fadeInUp"
                style={{ visibility: "visible", animationName: "fadeInUp" }}
              >
                <div className="fbox-ico-center ico-rounded-lg ico-45 bg-tra-purple purple-color">
                  <span className="flaticon-web-design"></span>
                </div>
                <div className="fbox-text-center">
                  <h5 className="h5-md">Actionable tools</h5>
                  <p className="p-lg">
                    The platform provide all the tools you need to get you
                    started, motivated and keep you going
                  </p>
                </div>
              </div>
            </div>
            <div className="col">
              <div
                className="fbox-3 pc-15 mb-40 wow fadeInUp"
                style={{ visibility: "visible", animationName: "fadeInUp" }}
              >
                <div className="fbox-ico-center ico-rounded-lg ico-45 bg-tra-purple purple-color">
                  <span className="flaticon-layers"></span>
                </div>
                <div className="fbox-text-center">
                  <h5 className="h5-md">Comprehensive Overview</h5>
                  <p className="p-lg">
                    The dashboard is detailed to let you see all the earnings
                    and results generated by your campeign
                  </p>
                </div>
              </div>
            </div>
            <div className="col">
              <div
                className="fbox-3 pc-15 mb-40 wow fadeInUp"
                style={{ visibility: "visible", animationName: "fadeInUp" }}
              >
                <div className="fbox-ico-center ico-rounded-lg ico-45 bg-tra-purple purple-color">
                  <span className="flaticon-email"></span>
                </div>
                <div className="fbox-text-center">
                  <h5 className="h5-md">Stunning Incentives</h5>
                  <p className="p-lg">
                    Your referral bonuses guarantees special incentives like car
                    awards, cash profits and many more.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Why;
